### ISSUE TITLE
blend() failing on non transparent images

### ISSUE THREAD

**Issue by nitsuga5124** [silvia-odwyer/photon#17]
blenc() panics on this line
https://github.com/silvia-odwyer/photon/blob/master/crate/src/helpers.rs#L47
when a non transparent image is given.

It panics with all jpg/jpeg images, but it doesn't panic on png images that are transparent

```rust
async fn pride_image(image_vec: &[u8], name: String) -> Result<Vec<u8>, Box<dyn std::error::Error>>{
    let mut og_image = PhotonImage::new_from_byteslice(image_vec.to_vec());
    let pride_path = format!("pride/{}.png", name);
    let mut pride_image = open_image(Box::leak(pride_path.into_boxed_str()));

    let og_image_arc = Arc::new(RwLock::new(&mut og_image));
    let og_image_clone = Arc::clone(&og_image_arc);
    let og_image_clone_clone = Arc::clone(&og_image_arc);

    block_in_place(move || {
        pride_image = {
            let og_x = og_image_clone_clone.read().unwrap().get_width();
            let og_y = og_image_clone_clone.read().unwrap().get_height();

            resize(&pride_image, og_x, og_y, SamplingFilter::Nearest)
        };

        let mut og_img_mut = og_image_clone.write().unwrap();

        blend(&mut og_img_mut, &pride_image, "overlay");
    });

    let mut result = Vec::new();

    let raw_pixels = og_image.get_raw_pixels();
    let width = og_image.get_width();
    let height = og_image.get_height();

    let img_buffer = image::ImageBuffer::from_vec(width, height, raw_pixels).unwrap();
    image::DynamicImage::ImageRgba8(img_buffer)
        .write_to(&mut result, image::ImageOutputFormat::Jpeg(255))?;

    Ok(result)
}
```
A fix for this or a possible workaround would be appreciated, as i can't figure out exactly the cause, and im unable to find a way to easily make the image transparent.

**Comment by silvia-odwyer** [comment]
Thanks for reporting this issue, @nitsuga5124! I've been investigating this issue and have attempted to recreate the bug. 

I've coded up a small example by blending two JPG images together with the "overlay" blend type, and it outputted the blended image successfully. That said, in the `blend` function, I'm not converting the second image parameter to RGBA so that could be a potential issue also, which I've fixed.

I've pushed up the changes to this repository, do you want to add `photon-rs` as a dependency in your `Cargo.toml` like this instead:

```toml
photon-rs = { git = "https://github.com/silvia-odwyer/photon" } 
```

You can try running your code again and see if it works. Let me know if it does, if not, I'll continue to investigate this further. Thanks again for reporting this, and for using Photon!

**Comment by nitsuga5124** [comment]
https://5124.16-b.it/ss/21:35:37_09-05-2020.png
It appears that the issue persist,
I've discovered 1 picture that's not transparent where the issue doesn't happen
but gray-scaling the image makes the issue occur.
It's still happening with every jpg/jpeg image I'm trying when combined with a png.

I can facilitate a zip with the images being used to test if required.

**Comment by silvia-odwyer** [comment]
If you could send a zip with the images being used, that would be great! @nitsuga5124 I can investigate the issue exactly then. 😄

**Comment by nitsuga5124** [comment]
```rust
reqwest.get(&url)
       .send()
       .await?
       .bytes()
       .await?
       .into_iter()
       .collect::<Vec<u8>>())
```
This is how the images get converted to the slice to be used on the function.

The zip contains the pride image saved on `pride_image` and the pictures that are given as a slice of u8 to the function argument.
[photon.zip](https://github.com/silvia-odwyer/photon/files/4604406/photon.zip)

**Comment by rsk700** [comment]
looks like problem because `new_from_byteslice` does not convert image to rgba before storing in PhotonImage, while both `open_image` and `dyn_image_from_raw` assume PhotonImage stores data in rgba format, I've attached my fix proposal

error mentioned in issue was because:
```
let img_buffer = ImageBuffer::from_vec(photon_image.width, photon_image.height, raw_pixels.to_vec()).unwrap();
```
checks for buf size (each pixel 4 components)
